# -*- coding: utf-8 -*-
"""week1-hack.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h7D_UfqEYJCOZ7Uk0NWyGgurOy0KZ5jg
"""

!pip install plotly kaleido -q

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import warnings

file_id = "1-J5-Af2pK1092F2TxCVMfvkkn43Gjr5V"
url = f"https://drive.google.com/uc?export=download&id={file_id}"

df = pd.read_csv(url, encoding='utf-8-sig')

print('✅ โหลดข้อมูลจาก Google Drive สำเร็จ!')

warnings.filterwarnings('ignore')

#ดาวน์โหลดฟอนต์ภาษาไทย (TH Sarabun New)
!wget -q https://github.com/Phonbopit/sarabun-webfont/raw/master/fonts/thsarabunnew-webfont.ttf
#เพิ่มฟอนต์เข้าไปในระบบ
mpl.font_manager.fontManager.addfont('thsarabunnew-webfont.ttf')
mpl.rc('font', family='TH Sarabun New', size=16)
sns.set_theme(style="whitegrid", font="TH Sarabun New")

# ตั้งค่า style
plt.rcParams['figure.dpi'] = 120

print('✅ Import สำเร็จ! พร้อมวิเคราะห์ข้อมูลแล้ว 🚀')

#import file and display
# df = pd.read_csv('import_export.csv', encoding='utf-8-sig')

print('=' * 60)
print('ข้อมูลการนำเข้า–ส่งออกสินค้าประมงของประเทศไทย')
print(f'   ➜ จำนวนแถว: {df.shape[0]:,} แถว | คอลัมน์: {df.shape[1]} คอลัมน์')
print(f'   ➜ คอลัมน์: {df.columns.tolist()}')
print('=' * 60)

print()
print('🔍 ตัวอย่างข้อมูล')
display(df.head(10))

"""ข้อ 1 — ตลาดส่งออกสินค้าประมงของไทยอยู่ที่ไหน?

จากข้อมูลมูลค่าการค้า จงสร้างกราฟที่แสดงให้เห็นว่า

1.1 ประเทศใดเป็น ตลาดส่งออกสินค้าประมงสำคัญของไทย

1.2 ประเทศใดเป็น แหล่งนำเข้าสัตว์น้ำหลักของไทย

1.3 และประเทศใดที่ไทย เกินดุลหรือขาดดุลการค้า ด้านสินค้าประมงอย่างชัดเจน
"""

#เตรียมข้อมูลแยกนำเข้าและส่งออก
export_df = df[df["tradeflow"] == 1]
print(f'ข้อมูลส่งออก มีจำนวนแถว: {export_df.shape[0]:,}')
display(export_df.head(5))
import_df = df[df["tradeflow"] == 2]
print(f'ข้อมูลน้ำเข้า มีจำนวนแถว: {import_df.shape[0]:,}')

"""1.1ประเทศใดเป็นตลาดส่งออกสินค้าประมงสำคัญของไทย"""

#จัดกลุ่มตามชื่อประเทศ เอาราคารวมมาบวกกัน แล้วเรียงจากมากไปน้อย เอามาโชว์ 10 ประเทศ
export_price = export_df.groupby("countryNameTH")["price"].sum().reset_index(name="total_price")

export_price_each = export_price.sort_values(by="total_price", ascending=False)
display(export_price_each.head(10))

export_box_graph = px.bar(export_price_each.head(10),
             x="countryNameTH",
             y="total_price")

export_box_graph.show()

"""จีน,นอร์เวย์,อินเดีย เป็นตลาดส่งออกสินค้าประมงสำคัญของไทย"""

#จัดกลุ่มตามชื่อประเทศ เอาราคารวมมาบวกกัน แล้วเรียงจากมากไปน้อย เอามาโชว์ 10 ประเทศ
import_price = import_df.groupby("countryNameTH")["price"].sum().reset_index(name="total_price")

import_price_each = import_price.sort_values(by="total_price", ascending=False)
display(import_price_each.head(10))

"""1.2 ประเทศใดเป็นแหล่งนำเข้าสัตว์น้ำหลักของไทย"""

import_box_graph = px.bar(import_price_each.head(10),
             x="countryNameTH",
             y="total_price")

import_box_graph.show()

"""ีusa,japan,china เป็นแหล่งนำเข้าสัตว์น้ำหลักของไทย

"""

#สร้างตารางใหม่ที่จัดกลุ่มตามประเทศ โดยเอาราคาน้ำเข้าและส่งออกมา merge ในตารางเดียวกัน แล้วค่อยคิดราคาดุลการค้า โดยเอาส่งออกตั้ง ลบด้วยน้ำเข้า
#เรียงจากน้อยไปมาก
trade = export_price.merge(import_price, on="countryNameTH", how="outer", suffixes=("_export", "_import"))
trade["trade_deficit"] = trade["total_price_import"] - trade["total_price_export"]
trade = trade.sort_values(by="trade_deficit", ascending=True)
display(trade.head(10))

"""1.3 ประเทศใดที่ไทยเกินดุลหรือขาดดุลการค้าด้านสินค้าประมงอย่างชัดเจน"""

#ประเทศที่ขาดดุลจะมี trade def เป็นลบ เลยเลือกเอาเฉพาะที่น้อยกว่า 0
#แล้วค่อยเทค absolute เข้าไป เพื่อให้เอามาทำเป็นกราฟดูง่ายๆ
#เอามาโชว์แค่ 10 ประเทศ จะได้ไม่รก
df_deficit = trade[trade["trade_deficit"] < 0].copy()
df_deficit["deficit_magnitude"] = df_deficit["trade_deficit"].abs()
trade_deficit_graph = px.bar(df_deficit.head(10),
             x="countryNameTH",
             y="deficit_magnitude")

trade_deficit_graph.show()

"""Norway

2.สินค้าประมงชนิดใดคือหัวใจของการค้าไทย?
"""

#จัดกลุ่มตาม heading11 โดยอาราคาของแต่ละสินค้ารวมไว้เป็นตัวๆ ทำแยกเป็นน้ำเข้ากับส่งออก
export_group = export_df.groupby("heading11")["price"].sum().reset_index(name="export_value")
import_group = import_df.groupby("heading11")["price"].sum().reset_index(name="import_value")

#เอาทั้งสองตารางมารวมกัน อาจมีบางสินค้าที่มีแค่ส่งออกแต่ไม่มีน้ำเข้า จึงเติมส่วนที่ว่างเป็น 0 แทน
merged = export_group.merge(import_group, on="heading11", how="outer").fillna(0)

# คำนวณดุลการค้า
merged["net_trade"] = merged["export_value"] - merged["import_value"]
display(merged.head(10))

#สร้างคอลลัมน์ใหม่ที่เอาไว้บอกว่าเกินดุลหรือขาดดุล แล้วเลือกเอาทอป 5 ของแต่ละประเภทมาแสดงโดยใช้abs
merged["type"] = merged["net_trade"].apply(lambda x: "Net Export" if x > 0 else "Net Import")
top = merged.sort_values(by="net_trade", key=abs, ascending=False).head(10)
#พอเป็น heading11 แล้วอ่านไม่ค่อยเข้าใจ เลยเอาชื่อไทยมาแปะเพิ่ม เพื่อให้อ่านงา่ยขึ้น
product_name = df[["heading11", "productDetailTH"]].drop_duplicates()
merged = merged.merge(product_name, on="heading11", how="left")

fig = px.bar(
    top,
    x="productDetailTH",
    y="net_trade",
    color="type",
    title="Fisheries Product Structure of Thailand (Net Export vs Import)",
    labels={"heading11": "HS Code", "net_trade": "Net Trade Value"}
)

fig.show()

"""Skipjack/Stripe-bellied bonito ไทยส่งออกมากกว่านำเข้า

tuna skipjack/atlantic bonito ไทยต้องพึ่งพาการนำเข้า

3.การค้าสัตว์น้ำมีฤดูกาลหรือไม่?
"""

#จัดกลุ่มตามเดือนกับประเภทการค้า แล้วเอาราคาของแต่ละเดือนมาบวกกัน
monthly = df.groupby(["month", "tradeflow"])["price"].sum().reset_index()
display(monthly)

#สลับให้ tradeflow มาเป็น collumn ให้เดือนเป็นอินเด็กซ์ แล้วเติมแต่ละค่าลงไป
pivot = monthly.pivot(index="month", columns="tradeflow", values="price").reset_index()
#เปลี่ยนใช่แต่ละคอลลัมน์ให้ถูกต้อง
pivot.columns = ["month", "export_value", "import_value"]
#ถ้ามีค่าว่างที่เกิดจาก pivot ให้เติมด้วย 0
pivot = pivot.fillna(0)

display(pivot)

#หาค่าสูงสุด-ต่ำสุดของการส่งออกและน้ำเข้า
# Export
peak_export = pivot.loc[pivot["export_value"].idxmax()]
low_export = pivot.loc[pivot["export_value"].idxmin()]

# Import
peak_import = pivot.loc[pivot["import_value"].idxmax()]
low_import = pivot.loc[pivot["import_value"].idxmin()]

print("Peak Export:", peak_export["month"])
print("Low Export:", low_export["month"])

print("Peak Import:", peak_import["month"])
print("Low Import:", low_import["month"])

#เอามาพลอทเป็นกราฟตามเส้นเวลาเพื่อดูว่าเกิดอะไรขึ้น
import plotly.express as px

fig = px.line(
    pivot,
    x="month",
    y=["export_value", "import_value"],
    title="Seasonal Trade Pattern of Fisheries Products (Thailand)",
    labels={"value": "Trade Value", "month": "Month"}
)

fig.show()

"""จากรูปจะเห็นว่าเวลาหรือฤดูกาลที่เปลี่ยนมีผลกับยอดส่งออกและนำเข้า"""

#คิดว่ายังเห็นไม่ชัดเจนเลยลองสร้าง heatmap ดูของแต่ละช่วงเวลาและแต่ละสินค้า
export_pivot = export_df.pivot_table(
    index="productDetailTH",
    columns="month",
    values="price",
    aggfunc="sum",
    fill_value=0
)

#แยกประภทสินค้า
def categorize(product):
    if "กุ้ง" in product:
        return "Shrimp"
    elif "ปลา" in product:
        return "Fish"
    elif "หอย" in product:
        return "Shellfish"
    else:
        return "Other"

df["category"] = df["productDetailTH"].apply(categorize)

export_pivot = df[df["tradeflow"] == 1].pivot_table(
    index="category",
    columns="month",
    values="price",
    aggfunc="sum",
    fill_value=0
)

top_products = df.groupby("productDetailTH")["price"].sum().nlargest(10).index

export_df_top = export_df[export_df["productDetailTH"].isin(top_products)]

export_pivot = export_df_top.pivot_table(
    index="productDetailTH",
    columns="month",
    values="price",
    aggfunc="sum",
    fill_value=0
)

fig = px.imshow(
    export_pivot,
    aspect="auto",
    title="Export Heatmap by Product",
    labels=dict(x="Month", y="Product", color="Export Value")
)

fig.show()

"""จากรูป จะเห็นว่าข้อมูลช่วงต่ำสุดของส่งออก(Low Export: 8)จะล้อไปตามรูปที่มืดลงช่วงเดือน 8
วิเคราะห์ว่าในช่วงกลางปีซึ่งเป็นฤดูมรสุมของไทย (ประมาณเดือน 6–9)
การออกเรือประมงทำได้ยาก ส่งผลให้ปริมาณสัตว์น้ำลดลง ก็เลยส่งออกลด
"""

import_pivot = df[df["tradeflow"] == 2].pivot_table(
    index="category",
    columns="month",
    values="price",
    aggfunc="sum",
    fill_value=0
)

fig_import = px.imshow(
    import_pivot,
    aspect="auto",
    title="Import Heatmap by Category",
    labels=dict(x="Month", y="Category", color="Import Value")
)

fig_import.show()

"""จากรูปจะเห็นว่าช่วงเดือน 5 ซึ่งเป็นช่วงก่อนเกิดมรสุมจะมีการนำเข้ามากกว่าปกติ
วิเคราะห์ว่าเพราะเป็นการกักตุนสินค้าก่อนเกิดมรสุม

4.ความสัมพันธ์ระหว่างราคาและปริมาณเป็นยังไง
"""

fig_export = px.scatter(
    export_df,
    x="quantity",
    y="price",
    title="Price vs Quantity (Export)",
    trendline="ols"  # เส้นแนวโน้ม
)

fig_export.show()

fig_import = px.scatter(
    import_df,
    x="quantity",
    y="price",
    title="Price vs Quantity (Import)",
    trendline="ols"
)

fig_import.show()

corr_export = export_df["quantity"].corr(export_df["price"])
corr_import = import_df["quantity"].corr(import_df["price"])

print("Export Correlation:", corr_export)
print("Import Correlation:", corr_import)

"""จากค่า Correlation วิเคราะห์ว่าที่ส่งออกน้อยเพราะส่วนใหญ่ประเทศไทยส่งออกให้กับประเทศในภูมิภาคและจีนซะส่วนใหญ่ เนื่องจากค่าขนส่งในภูมิภาคราคาถูกกว่าข้ามทวีป
ส่วนที่นำเข้าแพง ส่วนใหญ่ไทยนำเข้าจากอเมริกาและญี่ปุ่นซะเยอะ ซึ่งค่าขนส่งแพง จึงทำให้ correlation สูง
"""